services:
  postgres01:
    image: postgres:15
    command: [postgres, --max_connections=100]
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - postgres01_network
    ports:
      - 5432:5432
    volumes:
      - postgres01_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

volumes:
  postgres01_data:
    external: true

networks:
  postgres01_network:
    external: true